### ISSUE TITLE
ASR server connection timeout

### ISSUE THREAD

**Issue by dakshdrolia376** [dialogflow/asr-server#17]
I successfully setup the server using apahe2 and it's working fine . But the app stops after 2-3 hrs automatically and needs to be started again. Any help ?
The following error comes : 

packet_write_wait : Connection to 52.32.208.166 port 22 : Broken pipe

**Comment by viju2008** [comment]
Where you able to download the KALDI ASR Model Zip from api.ai  link. For me its saying 404 not found

**Comment by realill** [comment]
22 is ssh port. This probably mean, that you run server from you ssh session and then when it is disconnected server is killed. Try to run it in background or use screen or create /etc/init.d initialization script.

**Comment by zyb8543d** [comment]
i get this result:
```
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
```

what's wrong?

**Comment by realill** [comment]
This means that Apache server is up and running but nothing can be found at URL you provided. Likely because FastCGI is not working or configured properly.
