### ISSUE TITLE
503 error

### ISSUE THREAD

**Issue by lio14cha** [dialogflow/asr-server#36]
After all installation when i am running through server it shows after stop the recording.how to remove this error and follow the instructions on the server.
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
<hr>
<address>Apache/2.4.29 (Ubuntu) Server at localhost Port 80</address>
</body></html>

**Comment by realill** [comment]
See your apache error.log to narrow down the problem.

**Comment by lio14cha** [comment]
Thank you for your help.
